language: node_js
node_js: 14
matrix:
  include:
    - node: 10
      if: branch = master
cache:
- node_modules
- yarn
before_install:
  - sudo apt -y install p7zip-full
script:
- set -e
- yarn lint
- yarn checkprettier
- yarn test-ci
- yarn tsc --noEmit
- yarn build
- BUILT_TESTS=1 yarn built-test-ci
after_success:
- bash <(curl -s https://codecov.io/bash)
- cp ${TRAVIS_BUILD_DIR}/packages/jbrowse-web/build/test_data/config.json ${TRAVIS_BUILD_DIR}/packages/jbrowse-web/build/config.json
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET
  bucket: "jbrowse.org"
  local-dir: packages/jbrowse-web/build
  upload-dir: code/jb2/alpha/$TRAVIS_BRANCH
  on:
    repo: GMOD/jbrowse-components
    all_branches: true
